In [1]:
import numpy as np
import pandas as pd

In [2]:
## series of 1-D array

In [3]:
s = pd.Series([10,20,30,40])

In [4]:
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [5]:
pop = pd.Series([1444 , 1393 , 323 , 278],
                index = ["India","China","USA","Indonesia"],
                name = "population_millions"
               )

In [6]:
print(pop)

India        1444
China        1393
USA           323
Indonesia     278
Name: population_millions, dtype: int64

In [7]:
print(pop[pop>500])

India    1444
China    1393
Name: population_millions, dtype: int64

In [10]:
q1 = pd.Series({"laptops":120,"phones":340,"tablets":77})
q2 = pd.Series({"phones":44,"laptops":474,"watches":73})
print(q1+q2)

laptops    594.0
phones     384.0
tablets      NaN
watches      NaN
dtype: float64

In [11]:
## Dataframe

In [14]:
df = pd.DataFrame({
    "name":["Asha","Bill","Chen","Diya","Evan"],
    "dept":["IT","HR","IT","Finance","HR"],
    "salary":[52000,48000,47999,75000,50000],
    "city":["Delhi","Mumbai","Surat","Agra","Delhi"]
})

In [15]:
print(df)

   name     dept  salary    city
0  Asha       IT   52000   Delhi
1  Bill       HR   48000  Mumbai
2  Chen       IT   47999   Surat
3  Diya  Finance   75000    Agra
4  Evan       HR   50000   Delhi

In [16]:
print(df.shape)

(5, 4)

In [17]:
print(list(df.columns))

['name', 'dept', 'salary', 'city']

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   dept    5 non-null      object
 2   salary  5 non-null      int64
 3   city    5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [19]:
df.describe()

             salary
count      5.000000
mean   54599.800000
std    11524.031421
min    47999.000000
25%    48000.000000
50%    50000.000000
75%    52000.000000
max    75000.000000

In [20]:
df.head()

   name     dept  salary    city
0  Asha       IT   52000   Delhi
1  Bill       HR   48000  Mumbai
2  Chen       IT   47999   Surat
3  Diya  Finance   75000    Agra
4  Evan       HR   50000   Delhi

In [23]:
raw=pd.DataFrame({
    "order_id":["1001","1002","1003"],
    "amount":["2500","1800","3200"]
})

In [24]:
print(raw)

  order_id amount
0     1001   2500
1     1002   1800
2     1003   3200

In [25]:
print(raw["amount"].sum())

250018003200

In [26]:
clean=raw.copy()

In [27]:
clean["order_id"]=pd.to_numeric(clean["order_id"])
clean["amount"]=pd.to_numeric(clean["amount"])

In [28]:
print(clean.sum())

order_id    3006
amount      7500
dtype: int64

In [29]:
print(clean["amount"].sum())

7500

In [30]:
df

   name     dept  salary    city
0  Asha       IT   52000   Delhi
1  Bill       HR   48000  Mumbai
2  Chen       IT   47999   Surat
3  Diya  Finance   75000    Agra
4  Evan       HR   50000   Delhi

In [31]:
people = df.set_index("name")

In [32]:
people

         dept  salary    city
name
Asha       IT   52000   Delhi
Bill       HR   48000  Mumbai
Chen       IT   47999   Surat
Diya  Finance   75000    Agra
Evan       HR   50000   Delhi

In [33]:
print(people.loc[["Asha","Chen"]])

     dept  salary   city
name
Asha   IT   52000  Delhi
Chen   IT   47999  Surat

In [34]:
print(people.loc[["Asha"],["salary"]])

      salary
name
Asha   52000

In [35]:
print(people.iloc[0])

dept         IT
salary    52000
city      Delhi
Name: Asha, dtype: object

In [36]:
print(people.iloc[1])

dept          HR
salary     48000
city      Mumbai
Name: Bill, dtype: object

In [38]:
print(people.iloc[0:3],[0,2])

     dept  salary    city
name
Asha   IT   52000   Delhi
Bill   HR   48000  Mumbai
Chen   IT   47999   Surat [0, 2]

In [41]:
print(people[people["salary"]<49000])

     dept  salary    city
name
Bill   HR   48000  Mumbai
Chen   IT   47999   Surat

In [47]:
print(people[(people["dept"]=="IT")&(people["salary"]<49000)])

     dept  salary   city
name
Chen   IT   47999  Surat

In [48]:
print(people.query("dept == 'IT'"))

     dept  salary   city
name
Asha   IT   52000  Delhi
Chen   IT   47999  Surat

In [59]:
print(people.query("dept == 'IT' & salary < 49000 "))

     dept  salary   city
name
Chen   IT   47999  Surat

In [49]:
## Missing Data

In [50]:
messy = pd.DataFrame({
    "product":["pen","Book","Bag","lamp","Mug"],
    "price":[20,np.nan,850,1200,np.nan],
    "rating":[4.1,4.5,np.nan,4.5,3.9]
})

In [51]:
messy

  product   price  rating
0     pen    20.0     4.1
1    Book     NaN     4.5
2     Bag   850.0     NaN
3    lamp  1200.0     4.5
4     Mug     NaN     3.9

In [52]:
messy.isna().sum()

product    0
price      2
rating     1
dtype: int64

In [53]:
filled = messy.copy()

In [54]:
filled["price"]=filled["price"].fillna(filled["price"].mean())

In [57]:
filled["rating"]=filled["rating"].fillna(filled["rating"].median())

In [58]:
print(filled)

  product   price  rating
0     pen    20.0    4.10
1    Book   690.0    4.50
2     Bag   850.0    4.25
3    lamp  1200.0    4.50
4     Mug   690.0    3.90